model:
  base_learning_rate: 1.0e-6
  target: ldm.models.latentvae.Inpainting
  params:
    first_stage_key: image
    data_root: /scratch/gabe/imagenet_ldm/vq-f8
    embeded: vq-f8
    monitor: val/total_loss_ema
    post_match: False
    lossconfig:
      target: ldm.modules.losses.NLL
      params:
        kl_weight: 1e-6
        logvar_init: 0.0

    vae_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 128
        ddconfig:
          flat_latent_z: False
          efficient: True
          resamp_with_conv: True
          double_z: True
          z_channels: 128
          resolution: 32
          in_channels: 4
          out_ch: 4
          ch: 256
          ch_mult: [1, 2, 2, 4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions:  [16, 8, 4]
          num_heads: 4
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 16384
        ckpt_path: models/first_stage_models/vq-f8/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 24
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: /scratch/gabe/imagenet_ldm
        embeded: vq-f8
        config:
          size: 256
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        data_root: /scratch/gabe/imagenet_ldm
        embeded: vq-f8
        config:
          size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    max_epochs: 50